### ISSUE TITLE
Text too big with imagemagick

### ISSUE THREAD

**Issue by rtoenjes** [IndyIndyIndy/placeholder_images#1]
When using imagemagick as the image source the text is generated huge and is cut off a bit on the right side.

**Comment by IndyIndyIndy** [comment]
Could you give an example?

The margin left and right is currently smaller than the placeholder.com generated images. (maybe I should make this configurable)

But the algorithm should automatically scale the font size down if it is too wide for the image, so nothing gets cut off.

**Comment by IndyIndyIndy** [comment]
Fitting text in local image generation should now be handled much better with version 1.1.0.

**Comment by rtoenjes** [comment]
It is fixed now, thanks.
